### PR TITLE
Add options for shared directory

### PR DESCRIPTION
**Pull request by JemiloII**
Allows to have a single shared directory, rather than having individual directories.

### CODE REVIEW

**Comment by mk-pmb** [comment]
I think this is just one special instance of a bigger problem: configuring root directories based on the username. Instead of the `shared` flag, I propose a dictionary option `userPaths` that maps usernames to path patterns. I'll update this comment with more details in a few minutes.

**Comment by JemiloII** [comment]
Well I suppose we could have a `{ '*': '.' }` for all users. However, should we include anonymous with the \* or have to declare anonymous user if we wanted to share all directories; `{ '*': '.', anonymous: '.' }`

**Comment by mk-pmb** [comment]
What's the benefit of using an asterisk over an empty string as the default key? I think the empty string is even less likely to conflict with a username.

In my spec, if anonymous has no setting, ftpd would check the default, no magic. So If you'd like to separate anonymous from "all named users", you'd have to configure it:
`{ '': '.' }` = same directory for all users, even anonymous.
`{ '': 'users/', admin: '.', anonymous: 'guests/' }` = separate directories for named and anon users, admin can see both.
`{ '': '.', anonymous: false }` = named users only.

**Comment by alanszlosek** [comment]
What about modifying the PASS success callback to accept an optional "folder" parameter (https://github.com/alanszlosek/nodeftpd/blob/master/ftpd.js#L319)? Line 322 (https://github.com/alanszlosek/nodeftpd/blob/master/ftpd.js#L322) would have to change a bit, but it would allow the implementor to map usernames to folders however they want. Maybe they're storing the user folder path in a database along with the usernames+passwords ... if so, it'd be easy to pass the folder along.

**Comment by mk-pmb** [comment]
@alanszlosek : :+1: for an optional folder arg to the callback, but let's still have a config option for cases where that folder arg is false-y. (Probably `undefined` due to a plain "old" auth function that doesn't care about paths.)

On another note, let's name those functions so we can refer to them independent of line numbers.

**Comment by alanszlosek** [comment]
Looks like this fork has similar functionality, along with a ton of other features: https://github.com/sstur/nodeftpd Have you seen it? He seems like a much better project maintainer than I am :-)

**Comment by JemiloII** [comment]
His won't work without a key and cert files. I need to set those up, nor is it clear how to even make one.

**Comment by mk-pmb** [comment]
In case you want an "officially" signed cert, you can get a cert for your webserver from [Let's Encrypt](https://letsencrypt.org/) and then use that cert for ftpd. If you neither have nor want a web server on that domain, I think LE has a temporary one built-in.
If you prefer to sign your certs yourself and convince the clients to trust your certs, try TinyCA2. [Their website](http://tinyca.sm-zone.net/) seems to be unavailable today, but maybe your OS even has it packaged.
You can probably test your certs by pointing a browser to your ftpd as https://host:port/ . If the SSL is initiated first (I think FileZilla calls that "implicit"), the browser won't learn it's FTP until after you have verified the cert.

**Pull request closed without merging**
